# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: udaconnect.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10udaconnect.proto\"`\n\x0fLocationMessage\x12\x11\n\tperson_id\x18\x01 \x01(\x05\x12\x11\n\tlongitude\x18\x02 \x01(\t\x12\x10\n\x08latitude\x18\x03 \x01(\t\x12\x15\n\rcreation_time\x18\x04 \x01(\t\"L\n\rPersonMessage\x12\x12\n\nfirst_name\x18\x01 \x01(\t\x12\x11\n\tlast_name\x18\x02 \x01(\t\x12\x14\n\x0c\x63ompany_name\x18\x03 \x01(\t2{\n\x11UdaconnectService\x12\x35\n\x0f\x63reate_location\x12\x10.LocationMessage\x1a\x10.LocationMessage\x12/\n\rcreate_person\x12\x0e.PersonMessage\x1a\x0e.PersonMessageb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'udaconnect_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_LOCATIONMESSAGE']._serialized_start=20
  _globals['_LOCATIONMESSAGE']._serialized_end=116
  _globals['_PERSONMESSAGE']._serialized_start=118
  _globals['_PERSONMESSAGE']._serialized_end=194
  _globals['_UDACONNECTSERVICE']._serialized_start=196
  _globals['_UDACONNECTSERVICE']._serialized_end=319
# @@protoc_insertion_point(module_scope)
